[dataBase]
db_connection_type=QODBC
db_port=3306
db_databaseName=robotsystem
db_username=root2
db_password=hcx123456
db_host=127.0.0.1
[unity]
#传动比  10/64 保留了四位有效数字
#tranRatio1=0.1563
#tranRatio2=-0.1563
#tranRatio3=-0.1563
#分辨率
precision=1024
#采样频率
freqTime=0.1
#设备型号  1是新设备 0是旧设备 默认新设备
#新设备参数
equipType=1
#initvalue1=15972
#initvalue2=14750
#initvalue3=15250
##最新机器设备参数
initvalue1=8192
initvalue2=8192
initvalue3=8192
tranRatio1=-0.28
tranRatio2=-0.28
tranRatio3=-0.28
#y_rotation  伸展/屈曲
xLeft=-70
xRight=80
#x_rotation   桡侧偏/尺侧偏
yUp=20
yDown=-30
#z_rotation  外旋（旋后）/内旋（旋前）
zLeft=-80
zRight=80
#旧设备参数
#equipType=0
#initvalue1=47068
#initvalue2=75101
#initvalue3=12933
#当数据到X轴上的多少值时触发转向；输入>=TriggerThresholdX------触发转向
TriggerThresholdX=15
[udp]
unityIP=127.0.0.1
unityPort=9999
QTIP=127.0.0.1
QTPort=9999
[Qt]
#显示患者资料卡区域的列数
cards_col_num=5 
#显示患者资料卡区域的垂直、水平间隔
vertical_spacing=30
horizontal_spacing=30
#患者资料卡的放缩比率
scaleRatio = 1
